INSERT INTO ddhub.locations (country_isocode, region_isocode)
VALUES ('DE', 'BY'),
       ('RO', 'TS');

INSERT INTO ddhub.usergroups (name)
VALUES ('mail-sender'),
       ('ddhub-admin'),
       ('role-admin'),
       ('vacation-admin');

INSERT INTO ddhub.permissions (resource, access_level)
VALUES ('employees', 'WRITE'),
       ('protectedemployees', 'READ'),
       ('labels', 'DELETE'),
       ('usergroups', 'WRITE'),
       ('usergroups', 'DELETE'),
       ('vacations', 'READ'),
       ('vacations', 'WRITE'),
       ('vacations', 'DELETE'),
       ('vacationentitlements', 'READ'),
       ('vacationentitlements', 'WRITE'),
       ('vacationrequestadminapprovals', 'WRITE'),
       ('vacationrequests', 'READ'),
       ('vacationrequests', 'WRITE'),
       ('vacationrequests', 'DELETE'),
       ('vacationreports', 'READ'),
       ('vacationrequestapprovals', 'WRITE'),
       ('businessdomains', 'READ'),
       ('businessdomains', 'WRITE'),
       ('businessdomains', 'DELETE'),
       ('missionassignments', 'READ'),
       ('missionassignments', 'WRITE'),
       ('missionassignments', 'DELETE'),
       ('projects', 'READ'),
       ('projects', 'WRITE'),
       ('projects', 'DELETE'),
       ('mailboxes', 'READ'),
       ('mailboxes', 'WRITE'),
       ('mailboxes', 'DELETE'),
       ('notifications', 'READ'),
       ('notifications', 'WRITE'),
       ('countries', 'READ'),
       ('countries', 'WRITE'),
       ('regions', 'WRITE'),
       ('bankholidays', 'WRITE'),
       ('bankholidays', 'DELETE'),
       ('workloads', 'READ');

INSERT INTO ddhub.usergroup_permission (resource, access_level, user_group)
VALUES ('employees', 'WRITE', 'ddhub-admin'),
       ('protectedemployees', 'READ', 'ddhub-admin'),
       ('labels', 'DELETE', 'ddhub-admin'),
       ('usergroups', 'WRITE', 'ddhub-admin'),
       ('usergroups', 'DELETE', 'ddhub-admin'),
       ('vacations', 'READ', 'ddhub-admin'),
       ('vacations', 'WRITE', 'ddhub-admin'),
       ('vacations', 'DELETE', 'ddhub-admin'),
       ('vacationentitlements', 'READ', 'ddhub-admin'),
       ('vacationentitlements', 'WRITE', 'ddhub-admin'),
       ('vacationrequestadminapprovals', 'WRITE', 'ddhub-admin'),
       ('vacationrequests', 'READ', 'ddhub-admin'),
       ('vacationrequests', 'WRITE', 'ddhub-admin'),
       ('vacationrequests', 'DELETE', 'ddhub-admin'),
       ('vacationreports', 'READ', 'ddhub-admin'),
       ('vacationrequestapprovals', 'WRITE', 'ddhub-admin'),
       ('businessdomains', 'READ', 'ddhub-admin'),
       ('businessdomains', 'WRITE', 'ddhub-admin'),
       ('businessdomains', 'DELETE', 'ddhub-admin'),
       ('missionassignments', 'READ', 'ddhub-admin'),
       ('missionassignments', 'WRITE', 'ddhub-admin'),
       ('missionassignments', 'DELETE', 'ddhub-admin'),
       ('projects', 'READ', 'ddhub-admin'),
       ('projects', 'WRITE', 'ddhub-admin'),
       ('projects', 'DELETE', 'ddhub-admin'),
       ('mailboxes', 'READ', 'ddhub-admin'),
       ('mailboxes', 'WRITE', 'ddhub-admin'),
       ('mailboxes', 'DELETE', 'ddhub-admin'),
       ('notifications', 'READ', 'ddhub-admin'),
       ('notifications', 'WRITE', 'ddhub-admin'),
       ('countries', 'READ', 'ddhub-admin'),
       ('countries', 'WRITE', 'ddhub-admin'),
       ('regions', 'WRITE', 'ddhub-admin'),
       ('bankholidays', 'WRITE', 'ddhub-admin'),
       ('bankholidays', 'DELETE', 'ddhub-admin'),
       ('workloads', 'READ', 'ddhub-admin');